name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  fgt: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set up and run fgt
        run: |
          go get github.com/GeertJohan/fgt
          fgt gofmt -l ./

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Tidy
        run: go mod tidy

      - name: Generate
        run: go generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2